export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const CERRAR_SESION = 'CERRAR_SESION'

export const CREAR_PERSONA = 'CREAR_PERSONA'
export const LISTAR_PERSONA = 'LISTAR_PERSONA'
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONA'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
